run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - unconvert
    - goconst
    - gocyclo
    - dupl
    - goimports
    - misspell
    - lll
    - whitespace
    - gocritic

linters-settings:
  gosec:
    excludes:
      - G104
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 140
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/rkuthiala/shiro-automation

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: cmd/runtime/help.go
      linters:
        - govet
        - staticcheck
        - errcheck
        - unused
        - gosimple
        - ineffassign
        - unconvert
        - goconst
        - gocyclo
        - dupl
        - goimports
        - misspell
        - lll
        - whitespace
        - gocritic
    - path: vendor/
      linters:
        - govet
        - staticcheck
        - errcheck
        - unused
        - gosimple
        - ineffassign
        - unconvert
        - goconst
        - gocyclo
        - dupl
        - goimports
        - misspell
        - lll
        - whitespace
        - gocritic
