// Code generated by shiro build. DO NOT EDIT.
// This is a placeholder - run 'shiro build' to regenerate with actual modules.

package cli

import (
	"github.com/rkuthiala/shiro-automation/internal/modules"
	"github.com/rkuthiala/shiro-automation/pkg/ai"
	"github.com/rkuthiala/shiro-automation/pkg/data"
	"github.com/rkuthiala/shiro-automation/pkg/git"
	"github.com/rkuthiala/shiro-automation/pkg/print"
	"github.com/rkuthiala/shiro-automation/pkg/shell"
	"github.com/rkuthiala/shiro-automation/pkg/slack"
)

// registerAllModules registers all built-in and external modules
func registerAllModules(registry *modules.Registry) error {
	// Core modules
	if err := registry.Register("ai.generate", ai.NewAIModule()); err != nil {
		return err
	}
	if err := registry.Register("slack.notify", slack.NewSlackModule(false)); err != nil {
		return err
	}
	if err := registry.Register("git.diff", git.NewGitModule()); err != nil {
		return err
	}
	if err := registry.Register("print", print.NewPrintModule()); err != nil {
		return err
	}
	if err := registry.Register("shell.exec", shell.NewShellModule()); err != nil {
		return err
	}
	if err := registry.Register("data.store", data.NewDataModule(nil)); err != nil {
		return err
	}
	if err := registry.Register("data.load", data.NewDataModule(nil)); err != nil {
		return err
	}
	if err := registry.Register("data.delete", data.NewDataModule(nil)); err != nil {
		return err
	}
	if err := registry.Register("data.exists", data.NewDataModule(nil)); err != nil {
		return err
	}

	return nil
}

// getRegisteredModules returns list of registered module names
func getRegisteredModules() []string {
	return []string{
		"ai.generate",
		"slack.notify",
		"git.diff",
		"print",
		"shell.exec",
		"data.store",
		"data.load",
		"data.delete",
		"data.exists",
	}
}
