package modules

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// GenerateRegistry generates the registry_generated.go file
func GenerateRegistry(registryPath, outputPath string) error {
	// Load registry
	discoverer := NewDiscoverer(registryPath, nil)
	if err := discoverer.LoadRegistry(); err != nil {
		return fmt.Errorf("failed to load registry: %w", err)
	}

	// Generate code
	code := generateRegistryCode(discoverer.registry)

	// Ensure directory exists
	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	// Write file
	if err := os.WriteFile(outputPath, []byte(code), 0644); err != nil {
		return fmt.Errorf("failed to write generated file: %w", err)
	}

	return nil
}

// generateRegistryCode generates the Go source code
func generateRegistryCode(registry *RegistryConfig) string {
	var sb strings.Builder

	// Header
	sb.WriteString("// Code generated by shiro build. DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("// Generated at: %s\n\n", time.Now().Format(time.RFC3339)))
	sb.WriteString("package cli\n\n")

	// Imports
	sb.WriteString("import (\n")
	sb.WriteString("\t\"github.com/rkuthiala/shiro-automation/internal/modules\"\n")
	sb.WriteString("\t// Core built-in modules\n")
	sb.WriteString("\t\"github.com/rkuthiala/shiro-automation/pkg/ai\"\n")
	sb.WriteString("\t\"github.com/rkuthiala/shiro-automation/pkg/data\"\n")
	sb.WriteString("\t\"github.com/rkuthiala/shiro-automation/pkg/git\"\n")
	sb.WriteString("\t\"github.com/rkuthiala/shiro-automation/pkg/print\"\n")
	sb.WriteString("\t\"github.com/rkuthiala/shiro-automation/pkg/shell\"\n")
	sb.WriteString("\t\"github.com/rkuthiala/shiro-automation/pkg/slack\"\n")

	// External module imports
	externalModules := getExternalModules(registry)
	if len(externalModules) > 0 {
		sb.WriteString("\n\t// External modules added via 'shiro add module'\n")
		for name, config := range externalModules {
			alias := strings.ToLower(name)
			pkg := config.Package
			if pkg == "" {
				// Default: derive from source
				pkg = config.Source
			}
			sb.WriteString(fmt.Sprintf("\t%s \"%s\"\n", alias, pkg))
		}
	}

	sb.WriteString(")\n\n")

	// RegisterAllModules function (unexported)
	sb.WriteString("// registerAllModules registers all built-in and external modules\n")
	sb.WriteString("func registerAllModules(registry *modules.Registry) error {\n")

	// Register core modules
	sb.WriteString("\t// Core modules\n")
	sb.WriteString("\tif err := registry.Register(\"ai.generate\", ai.NewAIModule()); err != nil {\n")
	sb.WriteString("\t\treturn err\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\tif err := registry.Register(\"slack.notify\", slack.NewSlackModule(false)); err != nil {\n")
	sb.WriteString("\t\treturn err\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\tif err := registry.Register(\"git.diff\", git.NewGitModule()); err != nil {\n")
	sb.WriteString("\t\treturn err\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\tif err := registry.Register(\"print\", print.NewPrintModule()); err != nil {\n")
	sb.WriteString("\t\treturn err\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\tif err := registry.Register(\"shell.exec\", shell.NewShellModule()); err != nil {\n")
	sb.WriteString("\t\treturn err\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\tif err := registry.Register(\"data.store\", data.NewDataModule(nil)); err != nil {\n")
	sb.WriteString("\t\treturn err\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\tif err := registry.Register(\"data.load\", data.NewDataModule(nil)); err != nil {\n")
	sb.WriteString("\t\treturn err\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\tif err := registry.Register(\"data.delete\", data.NewDataModule(nil)); err != nil {\n")
	sb.WriteString("\t\treturn err\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\tif err := registry.Register(\"data.exists\", data.NewDataModule(nil)); err != nil {\n")
	sb.WriteString("\t\treturn err\n")
	sb.WriteString("\t}\n")

	// Register external modules
	if len(externalModules) > 0 {
		sb.WriteString("\n\t// External modules\n")
		for name, config := range externalModules {
			alias := strings.ToLower(name)
			factory := config.Factory
			if factory == "" {
				// Default factory name: New<Module>Module
				factory = fmt.Sprintf("New%sModule", strings.Title(name))
			}
			sb.WriteString(fmt.Sprintf("\tif err := registry.Register(\"%s\", %s.%s()); err != nil {\n", name, alias, factory))
			sb.WriteString("\t\treturn err\n")
			sb.WriteString("\t}\n")
		}
	}

	sb.WriteString("\n\treturn nil\n")
	sb.WriteString("}\n")

	// ListModules function for reporting
	sb.WriteString("\n// getRegisteredModules returns list of registered module names\n")
	sb.WriteString("func getRegisteredModules() []string {\n")
	sb.WriteString("\treturn []string{\n")
	sb.WriteString("\t\t\"ai.generate\",\n")
	sb.WriteString("\t\t\"slack.notify\",\n")
	sb.WriteString("\t\t\"git.diff\",\n")
	sb.WriteString("\t\t\"print\",\n")
	sb.WriteString("\t\t\"shell.exec\",\n")
	sb.WriteString("\t\t\"data.store\",\n")
	sb.WriteString("\t\t\"data.load\",\n")
	sb.WriteString("\t\t\"data.delete\",\n")
	sb.WriteString("\t\t\"data.exists\",\n")
	for name := range externalModules {
		sb.WriteString(fmt.Sprintf("\t\t\"%s\",\n", name))
	}
	sb.WriteString("\t}\n")
	sb.WriteString("}\n")

	return sb.String()
}

// getExternalModules returns only builtin type modules from registry
func getExternalModules(registry *RegistryConfig) map[string]ModuleConfig {
	external := make(map[string]ModuleConfig)
	if registry == nil || registry.Modules == nil {
		return external
	}

	for name, config := range registry.Modules {
		if config.Type == "builtin" && config.Package != "" {
			external[name] = config
		}
	}

	return external
}
